### ISSUE TITLE
Question: need help with running i2lines2 / i2spec4

### ISSUE THREAD

**Issue by herrmanthegerman** [Lightning469/Forkey-Iodine-Cell-Code#1]
Hi,
Thanks for saving and providing Forkey's iodine absorption spectrum code.

However, I'm struggling to run it. 

I tried to execute the `i2lines.exe` but get the error "_error while loading shared libraries: cyggfortran-3.dll: cannot open shared object file: No such file or directory_"

So I installed **cygwin** and all required libraries. 

Now when I run  `i2lines.exe` , nothing happens. It does not create any output (nor error messages).

Any ideas how to get this program running?

Thanks!

**Comment by Lightning469** [comment]
Hi herrmanthegerman,

Sorry for the rather late response, I've been traveling and haven't had the chance to respond back to my emails in a timely manner.

If you look at the source code, you'll see that the only times when you'll get a message is when R/P lines are reassigned to other FCF values. I followed the ReadMe and it's pretty straightforward, once you run i2lines2.exe, it should ask you to give the output file a name (preferably with an extension .txt to view it easily), and then it works its magic. Make sure that the file with all the FCFs and molecular constants is in the same directory as i2lines2.exe as well. 

You're sure that you're not getting any files in the same directory as the one in which you're running the program?

**Comment by herrmanthegerman** [comment]
Thank you for your prompt response, Lightning469. Currently I'm away from the computer on which I tried to run `i2lines.exe`. I'll report back in about two to three weeks.
